{% set name = "pixmappy" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gbernstein/pixmappy/archive/v{{ version }}.tar.gz
  sha256: 0626014e3b56a83d7f42ce16715f9acc2d99232d9790a5637bb5264429170b7a

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - future
    - astropy-base
    - scipy
    - pyyaml
    - lsstdesc.coord

test:
  imports:
    - pixmappy
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/gbernstein/pixmappy
  license: BSD-2-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - PIFF_LICENSE
  summary: 'Python interface to gbdes pixel map (astrometry) solutions'

extra:
  recipe-maintainers:
    - beckermr
